### ISSUE TITLE
Ereddicator changing comments in lieu of deleting

### ISSUE THREAD

**Issue by Brucenstein** [Jelly-Pudding/ereddicator#7]
Preface: This could ABSOLUTELY be user error.

Using the Windows .exe. I was able to successfully set up my Reddit script and run Ereddicator to replace all posts/comments with random text (and advertising!).

However, I am now trying to delete all these same comments. I am choosing what i believe to be the right settings for this - delete comments (which automatically un-checks edit comments) and delete posts (which automatically unchecks edit posts).

However, the output in the console is confusing. Most of the lines are still showing that they are editing comments rather than deleting them. Searching for my comments in communities shows that comments are still up. Notably, SOMETIMES the console will identify a comment as deleted but only about one in three (at best - sometimes it's more) seem to actually have been deleted - the others all still refer to (successfully) editing comments. See partial output below (community names removed).

Edit 1/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with advertising text.
Edit 3/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with random text.
Edit 2/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with random text.
Deleting comment: 'Comment 'Original Content erased u...' in [subreddit]'

Note that it is not always consistent with how many edits are in between each deletion (I've seen it go probably up to a dozen or more between noting such). E.g.:

Deleting comment: 'Comment 'lixioaf buvutdwjgs plkmvp...' in [subreddit]'
Edit 1/3: Editing comment 'Comment 'orbqhte rasaa prirx adfmu...' in [subreddit]' with advertising text.
Edit 2/3: Editing comment 'Comment 'gwore bkmnlp omdne qwslzq...' in [subreddit]' with advertising text.
Edit 2/3: Editing comment 'Comment 'orbqhte rasaa prirx adfmu...' in [subreddit]' with advertising text.
Edit 3/3: Editing comment 'Comment 'gwore bkmnlp omdne qwslzq...' in [subreddit]' with advertising text.
Edit 3/3: Editing comment 'Comment 'orbqhte rasaa prirx adfmu...' in [subreddit]' with advertising text.
Deleting comment: 'Comment 'gwore bkmnlp omdne qwslzq...' in [subreddit]'
Edit 1/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with advertising text.
Deleting comment: 'Comment 'orbqhte rasaa prirx adfmu...' in [subreddit]'
Edit 1/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with random text.
Edit 2/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with advertising text.
Edit 2/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with random text.
Edit 3/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with advertising text.
Edit 3/3: Editing comment 'Comment 'Original Content erased u...' in [subreddit]' with random text.
Deleting comment: 'Comment 'Original Content erased u...' in [subreddit]'
Edit 1/3: Editing comment 'Comment 'dslcnkhynk ehxpzmo yfa sf...' in [subreddit]' with random text.
Deleting comment: 'Comment 'Original Content erased u...' in [subreddit]'
Edit 1/3: Editing comment 'Comment 'fxspuslq yvi cavutqngpqd ...' in [subreddit]' with random text.
Edit 2/3: Editing comment 'Comment 'fxspuslq yvi cavutqngpqd ...' in [subreddit]' with advertising text.
Encountered a Reddit API Exception: RATELIMIT: "Looks like you've been doing that a lot. Take a break for 4 seconds before trying again." on field 'ratelimit'

After having run "delete mode" once prior I checked in certain communities and at least some comments are still there (I can't confirm whether the ones identified by Ereddicator as deleted were actually deleted but I assume so). I'm running "delete mode" now a second time and same deal - some comments show as edited, some as deleted. Note that batch output is showing only deletions though, at least on this run through (I can't verify from the last one). E.g.:

====Progress: 126 comments deleted, 0 edited out of 150 processed so far. There are 2243 comments to process in total.====

I'm using the same data file I used for the original run; is that perhaps the problem? I tried requesting another data file thinking that might help but unfortunately there's a 30 day wait period between requests. Note that I have not made any comments/etc. since the original data file was produced; I did accidentally add new upvotes once or twice but manually removed those.

If you need any more info let me know. Thanks again for the great tool!

**Comment by Jelly-Pudding** [comment]
Hello thanks for raising this.

```
However, the output in the console is confusing. Most of the lines are still showing that they are editing comments rather than deleting them.
```

Yeah sorry, that's confusing. When you select the delete option(s), it will *also* edit the content before deletion. I appreciate you had already edited the content with the script before. This is just an added paranoid measure to ensure the original content never gets seen as Reddit is capable of restoring deleted comments/posts... the trade off is it does mean it will take longer to run.

What's also confusing is in the logs Ereddicator will only show the deletions - it won't count the fact that it is also editing the content before removing it. Need to work on this...

```
Notably, SOMETIMES the console will identify a comment as deleted but only about one in three (at best - sometimes it's more) seem to actually have been deleted - the others all still refer to (successfully) editing comments.

Note that it is not always consistent with how many edits are in between each deletion (I've seen it go probably up to a dozen or more between noting such). E.g.:
```

So Ereddicator will be editing/deleting multiple comments at the same time. That's why the logs are confusing here. It will be deleting all the comments (after editing them first)... general note to myself to double check if it shows if it failed to delete any content...

```
After having run "delete mode" once prior I checked in certain communities and at least some comments are still there (I can't confirm whether the ones identified by Ereddicator as deleted were actually deleted but I assume so).
```

Was that delete done based off the reddit export? If not, that may explain it as Ereddicator would not have gone through all your content. But if it was, the unfortunate thing is Reddit is capable of restoring deleted content. The best you can hope for is it restores your content with the meaningless text you replaced it with. I *think* that becomes more likely the longer the comments/posts are left in their edited state, but I'm not certain.

Will have to look over this at the weekend.

**Comment by Brucenstein** [comment]
Thank you for the quick response!

I'm going to wait until it finishes this round and then check what comments of mine may still be active. So far all comments I've found (though I only checked a few) have shown the Ereddicator random text. I haven't checked posts yet.

Appreciate the note about editing then deleting - that's precisely why I ran the edit-only function first!

Do you know if there is there a way to see if a comment has been "restored"? e.g. might it have a new post date or similar? Happy to look through all this when it's done and try and discern if it'll help you troubleshoot.

Thanks again!

**Comment by Jelly-Pudding** [comment]
Hello,

I've made a few improvements:

- Show in the GUI itself that comments/posts are edited before deletion.
- Capture more clearly in the "batch" messages that comments/posts are edited before deletion.
- Ensure Ereddicator will show if there is ever a problem when fetching an item which will be edited/deleted.

```
Do you know if there is there a way to see if a comment has been "restored"? e.g. might it have a new post date or similar? Happy to look through all this when it's done and try and discern if it'll help you troubleshoot.
```

Good idea. After investigating this, there doesn't seem to be any reliable way to detect this sadly. I have tried this on my own account as I can also see some comments have returned (but they have returned to their edited state since I ran Ereddicator on my own account)... unfortunately, after retrieving one of these restored comments for inspection, the only relevant fields I see that the Reddit API shows is creation time and last edit time. The edit time is of course a lot more recent, but the creation time is accurate, and there's no other metadata indicating a restoration. When content is restored, it seems to keep all its original timestamps.

I will be closing this issue now, thanks for raising it.
